
// Code generated by _tools/gen_shims. DO NOT EDIT.

package testrunner

import "github.com/microsoft/typescript-go/internal/testrunner"
import _ "unsafe"

type CompilerBaselineRunner = testrunner.CompilerBaselineRunner
type CompilerTestType = testrunner.CompilerTestType
//go:linkname NewCompilerBaselineRunner github.com/microsoft/typescript-go/internal/testrunner.NewCompilerBaselineRunner
func NewCompilerBaselineRunner(testType testrunner.CompilerTestType, isSubmodule bool) *testrunner.CompilerBaselineRunner
type ParseTestFilesOptions = testrunner.ParseTestFilesOptions
type Runner = testrunner.Runner
const TestTypeConformance = testrunner.TestTypeConformance
const TestTypeRegression = testrunner.TestTypeRegression
