
// Code generated by _tools/gen_shims. DO NOT EDIT.

package logging

import "github.com/microsoft/typescript-go/internal/project/logging"
import "io"
import _ "unsafe"

type LogCollector = logging.LogCollector
type LogTree = logging.LogTree
type Logger = logging.Logger
//go:linkname NewLogTree github.com/microsoft/typescript-go/internal/project/logging.NewLogTree
func NewLogTree(name string) *logging.LogTree
//go:linkname NewLogger github.com/microsoft/typescript-go/internal/project/logging.NewLogger
func NewLogger(output io.Writer) logging.Logger
//go:linkname NewNopLogger github.com/microsoft/typescript-go/internal/project/logging.NewNopLogger
func NewNopLogger() logging.Logger
//go:linkname NewTestLogger github.com/microsoft/typescript-go/internal/project/logging.NewTestLogger
func NewTestLogger() logging.LogCollector
