
// Code generated by _tools/gen_shims. DO NOT EDIT.

package iovfs

import "github.com/microsoft/typescript-go/internal/vfs/iovfs"
import "io/fs"
import _ "unsafe"

//go:linkname From github.com/microsoft/typescript-go/internal/vfs/iovfs.From
func From(fsys fs.FS, useCaseSensitiveFileNames bool) iovfs.FsWithSys
type FsWithSys = iovfs.FsWithSys
type RealpathFS = iovfs.RealpathFS
type WritableFS = iovfs.WritableFS
