import type { PackageManifestContribution, PackageManifestSection } from './package-manifest-contributions'
import type { ComposeDSL, JsonBuilder } from '@/core/services/planner'
import type { ProjectConfig } from '@/schema/project-config'
import { makePackageName } from '@/brand/package-name'
import { finalizePackageJsonOrder } from '@/core/modifier/package-json-order'
import { collectPackageManifestContributions } from '@/core/modifier/package-manifest-contributions'
import {
  getReactRouterPackageContributions,
  getVueRouterPackageContributions,
} from '@/core/owners/router'
import { getScaffoldFamilyPackageContributions } from '@/core/owners/scaffold-family'
import {
  getReactStateManagementPackageContributions,
  getVueStateManagementPackageContributions,
} from '@/core/owners/state-management'
import {
  contributionTrace,
  ContributionUnitKind,
  WorkspaceBootstrapOwner,
} from '@/core/ownership/model'
import {
  getWorkspaceBootstrapPackageContributions,
  getWorkspaceRootPackageContributions,
} from '@/core/workspace-bootstrap'
import { isReactProject, isVueProject, isWorkspaceRootProject } from '@/utils/type-guard'

function baseFrontendPackageJson(config: ProjectConfig) {
  return {
    name: makePackageName(config.name),
    type: 'module',
    version: '0.0.0',
    description: `A ${config.type} project generated by create-yume`,
    license: 'MIT',
    engines: {
      node: '>=18.12.0',
    },
    scripts: {},
    dependencies: {},
    devDependencies: {},
  }
}

function baseWorkspaceRootPackageJson(config: ProjectConfig) {
  return {
    name: makePackageName(config.name),
    type: 'module',
    version: '0.0.0',
    license: 'MIT',
    scripts: {},
    devDependencies: {},
  }
}

function basePackageJson(config: ProjectConfig) {
  return isWorkspaceRootProject(config)
    ? baseWorkspaceRootPackageJson(config)
    : baseFrontendPackageJson(config)
}

export function getPackageManifestContributions(config: ProjectConfig): PackageManifestContribution[] {
  if (isWorkspaceRootProject(config)) {
    return getWorkspaceRootPackageContributions(config)
  }

  return [
    ...getScaffoldFamilyPackageContributions(config),
    ...getWorkspaceBootstrapPackageContributions(config),
    ...(isVueProject(config)
      ? [
          ...getVueStateManagementPackageContributions(config),
          ...getVueRouterPackageContributions(config),
        ]
      : []),
    ...(isReactProject(config)
      ? [
          ...getReactStateManagementPackageContributions(config),
          ...getReactRouterPackageContributions(config),
        ]
      : []),
  ]
}

export function collectPackageManifestForConfig(config: ProjectConfig) {
  return collectPackageManifestContributions({
    base: basePackageJson(config),
    contributions: getPackageManifestContributions(config),
  })
}

function addSectionEntries(
  draft: Record<string, unknown>,
  section: PackageManifestSection,
  entries: Record<string, unknown>,
) {
  const current = draft[section]
  const target = Object.prototype.toString.call(current) === '[object Object]'
    ? current as Record<string, unknown>
    : {}

  Object.assign(target, entries)
  draft[section] = target
}

function applyPackageContribution(entry: JsonBuilder, contribution: PackageManifestContribution) {
  for (const [key, value] of Object.entries(contribution.fields ?? {})) {
    entry.modify((draft) => {
      draft[key] = value
    }, contribution.ownership)
  }

  for (const [section, entries] of Object.entries(contribution.sections ?? {}) as Array<[PackageManifestSection, Record<string, unknown>]>) {
    entry.modify((draft) => {
      addSectionEntries(draft, section, entries)
    }, contribution.ownership)
  }
}

export function buildPackageJson(dsl: ComposeDSL, config: ProjectConfig) {
  const entry = dsl.json('package.json', contributionTrace(WorkspaceBootstrapOwner, ContributionUnitKind.JsonTextMutation))
    .base(() => basePackageJson(config))

  const packageContributions = getPackageManifestContributions(config)

  // Keep the structured collector on the production build path as the owner-aware
  // conflict/provenance boundary. PlanService still materializes package.json via
  // per-contribution reducers so dry-run can show reducer ownership; tests assert
  // the materialized output stays aligned with this collected manifest.
  collectPackageManifestForConfig(config)

  for (const contribution of packageContributions) {
    applyPackageContribution(entry, contribution)
  }

  function applyPackageJsonOrder(draft: Record<string, unknown>) {
    finalizePackageJsonOrder(draft)
  }

  entry.finalize(applyPackageJsonOrder)
}
