#!/usr/bin/env bash
set -euo pipefail

version="$(
  node -e '
const fs = require("fs");

const pkg = JSON.parse(fs.readFileSync("_packages/tsgo/package.json", "utf8"));
if (typeof pkg.version !== "string" || pkg.version.trim() === "") {
  console.error("version field is empty in _packages/tsgo/package.json");
  process.exit(1);
}

process.stdout.write(pkg.version.trim());
'
)"

cat <<EOF > etscore/version_generated.go
// Code generated by _tools/version-prepare.sh. DO NOT EDIT.

package etscore

const EffectVersion = "${version}"
EOF
