
// Code generated by _tools/gen_shims. DO NOT EDIT.

package lsutil

import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/checker"
import "github.com/microsoft/typescript-go/internal/compiler"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/ls/lsutil"
import "github.com/microsoft/typescript-go/internal/lsp/lsproto"
import _ "unsafe"

//go:linkname AssertHasRealPosition github.com/microsoft/typescript-go/internal/ls/lsutil.AssertHasRealPosition
func AssertHasRealPosition(node *ast.Node)
type CodeLensUserPreferences = lsutil.CodeLensUserPreferences
//go:linkname CompareImportsOrRequireStatements github.com/microsoft/typescript-go/internal/ls/lsutil.CompareImportsOrRequireStatements
func CompareImportsOrRequireStatements(s1 *ast.Statement, s2 *ast.Statement, comparer func(a string, b string) int) int
//go:linkname CompareModuleSpecifiers github.com/microsoft/typescript-go/internal/ls/lsutil.CompareModuleSpecifiers
func CompareModuleSpecifiers(m1 *ast.Expression, m2 *ast.Expression, comparer func(a string, b string) int) int
//go:linkname DetectModuleSpecifierCaseBySort github.com/microsoft/typescript-go/internal/ls/lsutil.DetectModuleSpecifierCaseBySort
func DetectModuleSpecifierCaseBySort(importDeclsByGroup [][]*ast.Statement, comparersToTest []func(a string, b string) int) (comparer func(a string, b string) int, isSorted bool)
//go:linkname DetectNamedImportOrganizationBySort github.com/microsoft/typescript-go/internal/ls/lsutil.DetectNamedImportOrganizationBySort
func DetectNamedImportOrganizationBySort(originalGroups []*ast.Statement, comparersToTest []func(a string, b string) int, typesToTest []lsutil.OrganizeImportsTypeOrder) (comparer func(a string, b string) int, typeOrder lsutil.OrganizeImportsTypeOrder, found bool)
type EditorSettings = lsutil.EditorSettings
var FileExtensionKindModifiers = lsutil.FileExtensionKindModifiers
//go:linkname FilterImportDeclarations github.com/microsoft/typescript-go/internal/ls/lsutil.FilterImportDeclarations
func FilterImportDeclarations(statements []*ast.Statement) []*ast.Statement
type FormatCodeSettings = lsutil.FormatCodeSettings
//go:linkname FromLSFormatOptions github.com/microsoft/typescript-go/internal/ls/lsutil.FromLSFormatOptions
func FromLSFormatOptions(f lsutil.FormatCodeSettings, opt *lsproto.FormattingOptions) lsutil.FormatCodeSettings
//go:linkname GetDefaultFormatCodeSettings github.com/microsoft/typescript-go/internal/ls/lsutil.GetDefaultFormatCodeSettings
func GetDefaultFormatCodeSettings() lsutil.FormatCodeSettings
//go:linkname GetDetectionLists github.com/microsoft/typescript-go/internal/ls/lsutil.GetDetectionLists
func GetDetectionLists(preferences lsutil.UserPreferences) (comparersToTest []func(a string, b string) int, typeOrdersToTest []lsutil.OrganizeImportsTypeOrder)
//go:linkname GetExternalModuleName github.com/microsoft/typescript-go/internal/ls/lsutil.GetExternalModuleName
func GetExternalModuleName(specifier *ast.Expression) string
//go:linkname GetFirstToken github.com/microsoft/typescript-go/internal/ls/lsutil.GetFirstToken
func GetFirstToken(node *ast.Node, sourceFile *ast.SourceFile) *ast.Node
//go:linkname GetImportDeclarationInsertIndex github.com/microsoft/typescript-go/internal/ls/lsutil.GetImportDeclarationInsertIndex
func GetImportDeclarationInsertIndex(sortedImports []*ast.Statement, newImport *ast.Statement, comparer func(a *ast.Statement, b *ast.Statement) int) int
//go:linkname GetImportSpecifierInsertionIndex github.com/microsoft/typescript-go/internal/ls/lsutil.GetImportSpecifierInsertionIndex
func GetImportSpecifierInsertionIndex(sortedImports []*ast.Node, newImport *ast.Node, comparer func(s1 *ast.Node, s2 *ast.Node) int) int
//go:linkname GetLastChild github.com/microsoft/typescript-go/internal/ls/lsutil.GetLastChild
func GetLastChild(node *ast.Node, sourceFile *ast.SourceFile) *ast.Node
//go:linkname GetLastToken github.com/microsoft/typescript-go/internal/ls/lsutil.GetLastToken
func GetLastToken(node *ast.Node, sourceFile *ast.SourceFile) *ast.Node
//go:linkname GetLastVisitedChild github.com/microsoft/typescript-go/internal/ls/lsutil.GetLastVisitedChild
func GetLastVisitedChild(node *ast.Node, sourceFile *ast.SourceFile) *ast.Node
//go:linkname GetNamedImportSpecifierComparer github.com/microsoft/typescript-go/internal/ls/lsutil.GetNamedImportSpecifierComparer
func GetNamedImportSpecifierComparer(preferences lsutil.UserPreferences, comparer func(a string, b string) int) func(s1 *ast.Node, s2 *ast.Node) int
//go:linkname GetNamedImportSpecifierComparerWithDetection github.com/microsoft/typescript-go/internal/ls/lsutil.GetNamedImportSpecifierComparerWithDetection
func GetNamedImportSpecifierComparerWithDetection(importDecl *ast.Node, sourceFile *ast.SourceFile, preferences lsutil.UserPreferences) (specifierComparer func(s1 *ast.Node, s2 *ast.Node) int, isSorted core.Tristate)
//go:linkname GetOrganizeImportsStringComparerWithDetection github.com/microsoft/typescript-go/internal/ls/lsutil.GetOrganizeImportsStringComparerWithDetection
func GetOrganizeImportsStringComparerWithDetection(originalImportDecls []*ast.Statement, preferences lsutil.UserPreferences) (comparer func(a string, b string) int, isSorted bool)
//go:linkname GetQuotePreference github.com/microsoft/typescript-go/internal/ls/lsutil.GetQuotePreference
func GetQuotePreference(sourceFile *ast.SourceFile, preferences lsutil.UserPreferences) lsutil.QuotePreference
//go:linkname GetSymbolKind github.com/microsoft/typescript-go/internal/ls/lsutil.GetSymbolKind
func GetSymbolKind(typeChecker *checker.Checker, symbol *ast.Symbol, location *ast.Node) lsutil.ScriptElementKind
//go:linkname GetSymbolModifiers github.com/microsoft/typescript-go/internal/ls/lsutil.GetSymbolModifiers
func GetSymbolModifiers(typeChecker *checker.Checker, symbol *ast.Symbol) lsutil.ScriptElementKindModifier
type IncludeInlayParameterNameHints = lsutil.IncludeInlayParameterNameHints
const IncludeInlayParameterNameHintsAll = lsutil.IncludeInlayParameterNameHintsAll
const IncludeInlayParameterNameHintsLiterals = lsutil.IncludeInlayParameterNameHintsLiterals
const IncludeInlayParameterNameHintsNone = lsutil.IncludeInlayParameterNameHintsNone
type IndentStyle = lsutil.IndentStyle
const IndentStyleBlock = lsutil.IndentStyleBlock
const IndentStyleNone = lsutil.IndentStyleNone
const IndentStyleSmart = lsutil.IndentStyleSmart
type InlayHintsPreferences = lsutil.InlayHintsPreferences
//go:linkname IsCompletedNode github.com/microsoft/typescript-go/internal/ls/lsutil.IsCompletedNode
func IsCompletedNode(n *ast.Node, sourceFile *ast.SourceFile) bool
//go:linkname IsNonContextualKeyword github.com/microsoft/typescript-go/internal/ls/lsutil.IsNonContextualKeyword
func IsNonContextualKeyword(token ast.Kind) bool
type JsxAttributeCompletionStyle = lsutil.JsxAttributeCompletionStyle
const JsxAttributeCompletionStyleAuto = lsutil.JsxAttributeCompletionStyleAuto
const JsxAttributeCompletionStyleBraces = lsutil.JsxAttributeCompletionStyleBraces
const JsxAttributeCompletionStyleNone = lsutil.JsxAttributeCompletionStyleNone
const JsxAttributeCompletionStyleUnknown = lsutil.JsxAttributeCompletionStyleUnknown
//go:linkname ModuleSpecifierToValidIdentifier github.com/microsoft/typescript-go/internal/ls/lsutil.ModuleSpecifierToValidIdentifier
func ModuleSpecifierToValidIdentifier(moduleSpecifier string, forceCapitalize bool) string
//go:linkname ModuleSymbolToValidIdentifier github.com/microsoft/typescript-go/internal/ls/lsutil.ModuleSymbolToValidIdentifier
func ModuleSymbolToValidIdentifier(moduleSymbol *ast.Symbol, forceCapitalize bool) string
//go:linkname NewDefaultUserPreferences github.com/microsoft/typescript-go/internal/ls/lsutil.NewDefaultUserPreferences
func NewDefaultUserPreferences() lsutil.UserPreferences
//go:linkname NodeIsASICandidate github.com/microsoft/typescript-go/internal/ls/lsutil.NodeIsASICandidate
func NodeIsASICandidate(node *ast.Node, file *ast.SourceFile) bool
type OrganizeImportsCaseFirst = lsutil.OrganizeImportsCaseFirst
const OrganizeImportsCaseFirstFalse = lsutil.OrganizeImportsCaseFirstFalse
const OrganizeImportsCaseFirstLower = lsutil.OrganizeImportsCaseFirstLower
const OrganizeImportsCaseFirstUpper = lsutil.OrganizeImportsCaseFirstUpper
type OrganizeImportsCollation = lsutil.OrganizeImportsCollation
const OrganizeImportsCollationOrdinal = lsutil.OrganizeImportsCollationOrdinal
const OrganizeImportsCollationUnicode = lsutil.OrganizeImportsCollationUnicode
type OrganizeImportsSort = lsutil.OrganizeImportsSort
const OrganizeImportsSortAuto = lsutil.OrganizeImportsSortAuto
const OrganizeImportsSortNatural = lsutil.OrganizeImportsSortNatural
const OrganizeImportsSortNaturalIgnoreCase = lsutil.OrganizeImportsSortNaturalIgnoreCase
const OrganizeImportsSortOrdinal = lsutil.OrganizeImportsSortOrdinal
const OrganizeImportsSortOrdinalIgnoreCase = lsutil.OrganizeImportsSortOrdinalIgnoreCase
type OrganizeImportsTypeOrder = lsutil.OrganizeImportsTypeOrder
const OrganizeImportsTypeOrderAuto = lsutil.OrganizeImportsTypeOrderAuto
const OrganizeImportsTypeOrderFirst = lsutil.OrganizeImportsTypeOrderFirst
const OrganizeImportsTypeOrderInline = lsutil.OrganizeImportsTypeOrderInline
const OrganizeImportsTypeOrderLast = lsutil.OrganizeImportsTypeOrderLast
//go:linkname ParseUserPreferences github.com/microsoft/typescript-go/internal/ls/lsutil.ParseUserPreferences
func ParseUserPreferences(items map[string]any) lsutil.UserPreferences
//go:linkname PositionBelongsToNode github.com/microsoft/typescript-go/internal/ls/lsutil.PositionBelongsToNode
func PositionBelongsToNode(candidate *ast.Node, position int, file *ast.SourceFile) bool
//go:linkname PositionIsASICandidate github.com/microsoft/typescript-go/internal/ls/lsutil.PositionIsASICandidate
func PositionIsASICandidate(pos int, context *ast.Node, file *ast.SourceFile) bool
//go:linkname ProbablyUsesSemicolons github.com/microsoft/typescript-go/internal/ls/lsutil.ProbablyUsesSemicolons
func ProbablyUsesSemicolons(file *ast.SourceFile) bool
type QuotePreference = lsutil.QuotePreference
const QuotePreferenceAuto = lsutil.QuotePreferenceAuto
const QuotePreferenceDouble = lsutil.QuotePreferenceDouble
//go:linkname QuotePreferenceFromString github.com/microsoft/typescript-go/internal/ls/lsutil.QuotePreferenceFromString
func QuotePreferenceFromString(str *ast.StringLiteral) lsutil.QuotePreference
const QuotePreferenceSingle = lsutil.QuotePreferenceSingle
const QuotePreferenceUnknown = lsutil.QuotePreferenceUnknown
//go:linkname ResolveOrganizeImportsSort github.com/microsoft/typescript-go/internal/ls/lsutil.ResolveOrganizeImportsSort
func ResolveOrganizeImportsSort(preferences lsutil.UserPreferences) lsutil.OrganizeImportsSort
type ScriptElementKind = lsutil.ScriptElementKind
const ScriptElementKindAlias = lsutil.ScriptElementKindAlias
const ScriptElementKindCallSignatureElement = lsutil.ScriptElementKindCallSignatureElement
const ScriptElementKindClassElement = lsutil.ScriptElementKindClassElement
const ScriptElementKindConstElement = lsutil.ScriptElementKindConstElement
const ScriptElementKindConstructSignatureElement = lsutil.ScriptElementKindConstructSignatureElement
const ScriptElementKindConstructorImplementationElement = lsutil.ScriptElementKindConstructorImplementationElement
const ScriptElementKindDirectory = lsutil.ScriptElementKindDirectory
const ScriptElementKindEnumElement = lsutil.ScriptElementKindEnumElement
const ScriptElementKindEnumMemberElement = lsutil.ScriptElementKindEnumMemberElement
const ScriptElementKindExternalModuleName = lsutil.ScriptElementKindExternalModuleName
const ScriptElementKindFunctionElement = lsutil.ScriptElementKindFunctionElement
const ScriptElementKindIndexSignatureElement = lsutil.ScriptElementKindIndexSignatureElement
const ScriptElementKindInterfaceElement = lsutil.ScriptElementKindInterfaceElement
const ScriptElementKindKeyword = lsutil.ScriptElementKindKeyword
const ScriptElementKindLabel = lsutil.ScriptElementKindLabel
const ScriptElementKindLetElement = lsutil.ScriptElementKindLetElement
const ScriptElementKindLink = lsutil.ScriptElementKindLink
const ScriptElementKindLinkName = lsutil.ScriptElementKindLinkName
const ScriptElementKindLinkText = lsutil.ScriptElementKindLinkText
const ScriptElementKindLocalClassElement = lsutil.ScriptElementKindLocalClassElement
const ScriptElementKindLocalFunctionElement = lsutil.ScriptElementKindLocalFunctionElement
const ScriptElementKindLocalVariableElement = lsutil.ScriptElementKindLocalVariableElement
const ScriptElementKindMemberAccessorVariableElement = lsutil.ScriptElementKindMemberAccessorVariableElement
const ScriptElementKindMemberFunctionElement = lsutil.ScriptElementKindMemberFunctionElement
const ScriptElementKindMemberGetAccessorElement = lsutil.ScriptElementKindMemberGetAccessorElement
const ScriptElementKindMemberSetAccessorElement = lsutil.ScriptElementKindMemberSetAccessorElement
const ScriptElementKindMemberVariableElement = lsutil.ScriptElementKindMemberVariableElement
type ScriptElementKindModifier = lsutil.ScriptElementKindModifier
const ScriptElementKindModifierAbstract = lsutil.ScriptElementKindModifierAbstract
const ScriptElementKindModifierAmbient = lsutil.ScriptElementKindModifierAmbient
const ScriptElementKindModifierCjs = lsutil.ScriptElementKindModifierCjs
const ScriptElementKindModifierCts = lsutil.ScriptElementKindModifierCts
const ScriptElementKindModifierDcts = lsutil.ScriptElementKindModifierDcts
const ScriptElementKindModifierDeprecated = lsutil.ScriptElementKindModifierDeprecated
const ScriptElementKindModifierDmts = lsutil.ScriptElementKindModifierDmts
const ScriptElementKindModifierDts = lsutil.ScriptElementKindModifierDts
const ScriptElementKindModifierExported = lsutil.ScriptElementKindModifierExported
const ScriptElementKindModifierJs = lsutil.ScriptElementKindModifierJs
const ScriptElementKindModifierJson = lsutil.ScriptElementKindModifierJson
const ScriptElementKindModifierJsx = lsutil.ScriptElementKindModifierJsx
const ScriptElementKindModifierMjs = lsutil.ScriptElementKindModifierMjs
const ScriptElementKindModifierMts = lsutil.ScriptElementKindModifierMts
const ScriptElementKindModifierNone = lsutil.ScriptElementKindModifierNone
const ScriptElementKindModifierOptional = lsutil.ScriptElementKindModifierOptional
const ScriptElementKindModifierPrivate = lsutil.ScriptElementKindModifierPrivate
const ScriptElementKindModifierProtected = lsutil.ScriptElementKindModifierProtected
const ScriptElementKindModifierPublic = lsutil.ScriptElementKindModifierPublic
const ScriptElementKindModifierStatic = lsutil.ScriptElementKindModifierStatic
const ScriptElementKindModifierTs = lsutil.ScriptElementKindModifierTs
const ScriptElementKindModifierTsx = lsutil.ScriptElementKindModifierTsx
const ScriptElementKindModuleElement = lsutil.ScriptElementKindModuleElement
const ScriptElementKindParameterElement = lsutil.ScriptElementKindParameterElement
const ScriptElementKindPrimitiveType = lsutil.ScriptElementKindPrimitiveType
const ScriptElementKindScriptElement = lsutil.ScriptElementKindScriptElement
const ScriptElementKindString = lsutil.ScriptElementKindString
const ScriptElementKindTypeElement = lsutil.ScriptElementKindTypeElement
const ScriptElementKindTypeParameterElement = lsutil.ScriptElementKindTypeParameterElement
const ScriptElementKindUnknown = lsutil.ScriptElementKindUnknown
const ScriptElementKindVariableAwaitUsingElement = lsutil.ScriptElementKindVariableAwaitUsingElement
const ScriptElementKindVariableElement = lsutil.ScriptElementKindVariableElement
const ScriptElementKindVariableUsingElement = lsutil.ScriptElementKindVariableUsingElement
const ScriptElementKindWarning = lsutil.ScriptElementKindWarning
type SemicolonPreference = lsutil.SemicolonPreference
const SemicolonPreferenceIgnore = lsutil.SemicolonPreferenceIgnore
const SemicolonPreferenceInsert = lsutil.SemicolonPreferenceInsert
const SemicolonPreferenceRemove = lsutil.SemicolonPreferenceRemove
//go:linkname ShouldUseUriStyleNodeCoreModules github.com/microsoft/typescript-go/internal/ls/lsutil.ShouldUseUriStyleNodeCoreModules
func ShouldUseUriStyleNodeCoreModules(file *ast.SourceFile, program *compiler.Program) core.Tristate
//go:linkname SyntaxMayBeASICandidate github.com/microsoft/typescript-go/internal/ls/lsutil.SyntaxMayBeASICandidate
func SyntaxMayBeASICandidate(kind ast.Kind) bool
//go:linkname SyntaxRequiresTrailingCommaOrSemicolonOrASI github.com/microsoft/typescript-go/internal/ls/lsutil.SyntaxRequiresTrailingCommaOrSemicolonOrASI
func SyntaxRequiresTrailingCommaOrSemicolonOrASI(kind ast.Kind) bool
//go:linkname SyntaxRequiresTrailingFunctionBlockOrSemicolonOrASI github.com/microsoft/typescript-go/internal/ls/lsutil.SyntaxRequiresTrailingFunctionBlockOrSemicolonOrASI
func SyntaxRequiresTrailingFunctionBlockOrSemicolonOrASI(kind ast.Kind) bool
//go:linkname SyntaxRequiresTrailingModuleBlockOrSemicolonOrASI github.com/microsoft/typescript-go/internal/ls/lsutil.SyntaxRequiresTrailingModuleBlockOrSemicolonOrASI
func SyntaxRequiresTrailingModuleBlockOrSemicolonOrASI(kind ast.Kind) bool
//go:linkname SyntaxRequiresTrailingSemicolonOrASI github.com/microsoft/typescript-go/internal/ls/lsutil.SyntaxRequiresTrailingSemicolonOrASI
func SyntaxRequiresTrailingSemicolonOrASI(kind ast.Kind) bool
type UserPreferences = lsutil.UserPreferences
