
// Code generated by _tools/gen_shims. DO NOT EDIT.

package repo

import "github.com/microsoft/typescript-go/internal/repo"
import _ "unsafe"

//go:linkname RootPath github.com/microsoft/typescript-go/internal/repo.RootPath
func RootPath() string
//go:linkname SkipIfNoTypeScriptSubmodule github.com/microsoft/typescript-go/internal/repo.SkipIfNoTypeScriptSubmodule
func SkipIfNoTypeScriptSubmodule(t repo.SkippableTest)
type SkippableTest = repo.SkippableTest
//go:linkname TestDataPath github.com/microsoft/typescript-go/internal/repo.TestDataPath
func TestDataPath() string
//go:linkname TypeScriptSubmoduleExists github.com/microsoft/typescript-go/internal/repo.TypeScriptSubmoduleExists
func TypeScriptSubmoduleExists() bool
//go:linkname TypeScriptSubmodulePath github.com/microsoft/typescript-go/internal/repo.TypeScriptSubmodulePath
func TypeScriptSubmodulePath() string
