
// Code generated by _tools/gen_shims. DO NOT EDIT.

package lsp

import "github.com/microsoft/typescript-go/internal/lsp"
import "io"
import _ "unsafe"

//go:linkname NewServer github.com/microsoft/typescript-go/internal/lsp.NewServer
func NewServer(opts *lsp.ServerOptions) *lsp.Server
type Reader = lsp.Reader
type Server = lsp.Server
type ServerOptions = lsp.ServerOptions
//go:linkname ToReader github.com/microsoft/typescript-go/internal/lsp.ToReader
func ToReader(r io.Reader) lsp.Reader
//go:linkname ToWriter github.com/microsoft/typescript-go/internal/lsp.ToWriter
func ToWriter(w io.Writer) lsp.Writer
type Writer = lsp.Writer
