
// Code generated by _tools/gen_shims. DO NOT EDIT.

package api

import "github.com/microsoft/typescript-go/internal/api"
import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/checker"
import "github.com/microsoft/typescript-go/internal/project"
import "io"
import _ "unsafe"

type APIFileChangeSummary = api.APIFileChangeSummary
type APIFileChanges = api.APIFileChanges
type AsyncConn = api.AsyncConn
type CheckerNodeParams = api.CheckerNodeParams
type CheckerSignatureParams = api.CheckerSignatureParams
type CheckerSymbolParams = api.CheckerSymbolParams
type CheckerTypeParams = api.CheckerTypeParams
type CompletionEntryLabelDetailsResponse = api.CompletionEntryLabelDetailsResponse
type CompletionEntryResponse = api.CompletionEntryResponse
type CompletionInfoResponse = api.CompletionInfoResponse
type ConfigFileResponse = api.ConfigFileResponse
type Conn = api.Conn
type DiagnosticResponse = api.DiagnosticResponse
type DocumentIdentifier = api.DocumentIdentifier
var ErrClientError = api.ErrClientError
var ErrConnClosed = api.ErrConnClosed
var ErrInvalidRequest = api.ErrInvalidRequest
var ErrRequestTimeout = api.ErrRequestTimeout
//go:linkname GeneratePipePath github.com/microsoft/typescript-go/internal/api.GeneratePipePath
func GeneratePipePath(name string) string
type GetBaseTypeOfLiteralTypeParams = api.GetBaseTypeOfLiteralTypeParams
type GetCompletionsAtPositionParams = api.GetCompletionsAtPositionParams
type GetContextualTypeParams = api.GetContextualTypeParams
type GetDefaultProjectForFileParams = api.GetDefaultProjectForFileParams
type GetDiagnosticsParams = api.GetDiagnosticsParams
type GetIntrinsicTypeParams = api.GetIntrinsicTypeParams
type GetMemberInModuleExportsParams = api.GetMemberInModuleExportsParams
type GetNonNullableTypeParams = api.GetNonNullableTypeParams
type GetParameterTypeParams = api.GetParameterTypeParams
type GetProjectDiagnosticsParams = api.GetProjectDiagnosticsParams
type GetPropertyOfTypeParams = api.GetPropertyOfTypeParams
type GetReferencedSymbolsForNodeParams = api.GetReferencedSymbolsForNodeParams
type GetReferencesToSymbolInFileParams = api.GetReferencesToSymbolInFileParams
type GetResolvedSignatureParams = api.GetResolvedSignatureParams
type GetSignaturePropertyParams = api.GetSignaturePropertyParams
type GetSignatureUsagesParams = api.GetSignatureUsagesParams
type GetSignaturesOfTypeParams = api.GetSignaturesOfTypeParams
type GetSourceFileNamesParams = api.GetSourceFileNamesParams
type GetSourceFileParams = api.GetSourceFileParams
type GetSymbolAtLocationParams = api.GetSymbolAtLocationParams
type GetSymbolAtPositionParams = api.GetSymbolAtPositionParams
type GetSymbolPropertyParams = api.GetSymbolPropertyParams
type GetSymbolsAtLocationsParams = api.GetSymbolsAtLocationsParams
type GetSymbolsAtPositionsParams = api.GetSymbolsAtPositionsParams
type GetTypeAtLocationParams = api.GetTypeAtLocationParams
type GetTypeAtLocationsParams = api.GetTypeAtLocationsParams
type GetTypeAtPositionParams = api.GetTypeAtPositionParams
type GetTypeFromTypeNodeParams = api.GetTypeFromTypeNodeParams
type GetTypeOfSymbolAtLocationParams = api.GetTypeOfSymbolAtLocationParams
type GetTypeOfSymbolParams = api.GetTypeOfSymbolParams
type GetTypePropertyParams = api.GetTypePropertyParams
type GetTypesAtPositionsParams = api.GetTypesAtPositionsParams
type GetTypesOfSymbolsParams = api.GetTypesOfSymbolsParams
type GetWidenedTypeParams = api.GetWidenedTypeParams
type Handler = api.Handler
type IndexInfoResponse = api.IndexInfoResponse
type InitializeResponse = api.InitializeResponse
type IsArrayLikeTypeParams = api.IsArrayLikeTypeParams
type IsTypeAssignableToParams = api.IsTypeAssignableToParams
type JSDocTagInfo = api.JSDocTagInfo
type JSONRPCProtocol = api.JSONRPCProtocol
type Message = api.Message
type MessagePackProtocol = api.MessagePackProtocol
type MessageType = api.MessageType
const MessageTypeCall = api.MessageTypeCall
const MessageTypeCallError = api.MessageTypeCallError
const MessageTypeCallResponse = api.MessageTypeCallResponse
const MessageTypeError = api.MessageTypeError
const MessageTypeRequest = api.MessageTypeRequest
const MessageTypeResponse = api.MessageTypeResponse
const MessageTypeUnknown = api.MessageTypeUnknown
type Method = api.Method
const MethodGetAliasSymbolOfType = api.MethodGetAliasSymbolOfType
const MethodGetAliasTypeArgumentsOfType = api.MethodGetAliasTypeArgumentsOfType
const MethodGetAliasedSymbol = api.MethodGetAliasedSymbol
const MethodGetAnyType = api.MethodGetAnyType
const MethodGetApparentType = api.MethodGetApparentType
const MethodGetBaseConstraintOfType = api.MethodGetBaseConstraintOfType
const MethodGetBaseTypeOfLiteralType = api.MethodGetBaseTypeOfLiteralType
const MethodGetBaseTypeOfType = api.MethodGetBaseTypeOfType
const MethodGetBaseTypes = api.MethodGetBaseTypes
const MethodGetBigIntType = api.MethodGetBigIntType
const MethodGetBindDiagnostics = api.MethodGetBindDiagnostics
const MethodGetBooleanType = api.MethodGetBooleanType
const MethodGetCheckTypeOfType = api.MethodGetCheckTypeOfType
const MethodGetCompletionsAtPosition = api.MethodGetCompletionsAtPosition
const MethodGetConfigFileParsingDiagnostics = api.MethodGetConfigFileParsingDiagnostics
const MethodGetConstantValue = api.MethodGetConstantValue
const MethodGetConstraintOfType = api.MethodGetConstraintOfType
const MethodGetConstraintOfTypeParameter = api.MethodGetConstraintOfTypeParameter
const MethodGetContextualType = api.MethodGetContextualType
const MethodGetDeclarationDiagnostics = api.MethodGetDeclarationDiagnostics
const MethodGetDeclaredTypeOfSymbol = api.MethodGetDeclaredTypeOfSymbol
const MethodGetDefaultProjectForFile = api.MethodGetDefaultProjectForFile
const MethodGetDocumentationComment = api.MethodGetDocumentationComment
const MethodGetESSymbolType = api.MethodGetESSymbolType
const MethodGetExportSpecifierLocalTarget = api.MethodGetExportSpecifierLocalTarget
const MethodGetExportSymbolOfSymbol = api.MethodGetExportSymbolOfSymbol
const MethodGetExportsOfModule = api.MethodGetExportsOfModule
const MethodGetExportsOfSymbol = api.MethodGetExportsOfSymbol
const MethodGetExtendsTypeOfType = api.MethodGetExtendsTypeOfType
const MethodGetFalseTypeOfConditionalType = api.MethodGetFalseTypeOfConditionalType
const MethodGetFreshTypeOfType = api.MethodGetFreshTypeOfType
const MethodGetGlobalDiagnostics = api.MethodGetGlobalDiagnostics
const MethodGetImmediateAliasedSymbol = api.MethodGetImmediateAliasedSymbol
const MethodGetIndexInfosOfType = api.MethodGetIndexInfosOfType
const MethodGetIndexTypeOfType = api.MethodGetIndexTypeOfType
const MethodGetJSDocTags = api.MethodGetJSDocTags
const MethodGetLocalTypeParametersOfType = api.MethodGetLocalTypeParametersOfType
const MethodGetMemberInModuleExports = api.MethodGetMemberInModuleExports
const MethodGetMembersOfSymbol = api.MethodGetMembersOfSymbol
const MethodGetNeverType = api.MethodGetNeverType
const MethodGetNonNullableType = api.MethodGetNonNullableType
const MethodGetNullType = api.MethodGetNullType
const MethodGetNumberType = api.MethodGetNumberType
const MethodGetObjectTypeOfType = api.MethodGetObjectTypeOfType
const MethodGetOuterTypeParametersOfType = api.MethodGetOuterTypeParametersOfType
const MethodGetParameterType = api.MethodGetParameterType
const MethodGetParametersOfSignature = api.MethodGetParametersOfSignature
const MethodGetParentOfSymbol = api.MethodGetParentOfSymbol
const MethodGetProgramDiagnostics = api.MethodGetProgramDiagnostics
const MethodGetPropertiesOfType = api.MethodGetPropertiesOfType
const MethodGetPropertyOfType = api.MethodGetPropertyOfType
const MethodGetReferencedSymbolsForNode = api.MethodGetReferencedSymbolsForNode
const MethodGetReferencesToSymbolInFile = api.MethodGetReferencesToSymbolInFile
const MethodGetRegularTypeOfType = api.MethodGetRegularTypeOfType
const MethodGetResolvedSignature = api.MethodGetResolvedSignature
const MethodGetRestTypeOfSignature = api.MethodGetRestTypeOfSignature
const MethodGetReturnTypeOfSignature = api.MethodGetReturnTypeOfSignature
const MethodGetSemanticDiagnostics = api.MethodGetSemanticDiagnostics
const MethodGetServerTiming = api.MethodGetServerTiming
const MethodGetShorthandAssignmentValueSymbol = api.MethodGetShorthandAssignmentValueSymbol
const MethodGetSignatureFromDeclaration = api.MethodGetSignatureFromDeclaration
const MethodGetSignatureUsages = api.MethodGetSignatureUsages
const MethodGetSignaturesOfType = api.MethodGetSignaturesOfType
const MethodGetSourceFile = api.MethodGetSourceFile
const MethodGetSourceFileMetadata = api.MethodGetSourceFileMetadata
const MethodGetSourceFileNames = api.MethodGetSourceFileNames
const MethodGetStringType = api.MethodGetStringType
const MethodGetSuggestionDiagnostics = api.MethodGetSuggestionDiagnostics
const MethodGetSymbolAtLocation = api.MethodGetSymbolAtLocation
const MethodGetSymbolAtPosition = api.MethodGetSymbolAtPosition
const MethodGetSymbolOfType = api.MethodGetSymbolOfType
const MethodGetSymbolsAtLocations = api.MethodGetSymbolsAtLocations
const MethodGetSymbolsAtPositions = api.MethodGetSymbolsAtPositions
const MethodGetSyntacticDiagnostics = api.MethodGetSyntacticDiagnostics
const MethodGetTargetOfSignature = api.MethodGetTargetOfSignature
const MethodGetTargetOfType = api.MethodGetTargetOfType
const MethodGetThisParameterOfSignature = api.MethodGetThisParameterOfSignature
const MethodGetTrueTypeOfConditionalType = api.MethodGetTrueTypeOfConditionalType
const MethodGetTypeArguments = api.MethodGetTypeArguments
const MethodGetTypeAtLocation = api.MethodGetTypeAtLocation
const MethodGetTypeAtLocations = api.MethodGetTypeAtLocations
const MethodGetTypeAtPosition = api.MethodGetTypeAtPosition
const MethodGetTypeFromTypeNode = api.MethodGetTypeFromTypeNode
const MethodGetTypeOfSymbol = api.MethodGetTypeOfSymbol
const MethodGetTypeOfSymbolAtLocation = api.MethodGetTypeOfSymbolAtLocation
const MethodGetTypeParametersOfSignature = api.MethodGetTypeParametersOfSignature
const MethodGetTypeParametersOfType = api.MethodGetTypeParametersOfType
const MethodGetTypePredicateOfSignature = api.MethodGetTypePredicateOfSignature
const MethodGetTypesAtPositions = api.MethodGetTypesAtPositions
const MethodGetTypesOfSymbols = api.MethodGetTypesOfSymbols
const MethodGetTypesOfType = api.MethodGetTypesOfType
const MethodGetUndefinedType = api.MethodGetUndefinedType
const MethodGetUnknownType = api.MethodGetUnknownType
const MethodGetVoidType = api.MethodGetVoidType
const MethodGetWellKnownSymbols = api.MethodGetWellKnownSymbols
const MethodGetWidenedType = api.MethodGetWidenedType
const MethodInitialize = api.MethodInitialize
const MethodIsArrayLikeType = api.MethodIsArrayLikeType
const MethodIsArrayType = api.MethodIsArrayType
const MethodIsContextSensitive = api.MethodIsContextSensitive
const MethodIsTupleType = api.MethodIsTupleType
const MethodIsTypeAssignableTo = api.MethodIsTypeAssignableTo
const MethodParseConfigFile = api.MethodParseConfigFile
const MethodPrintNode = api.MethodPrintNode
const MethodRelease = api.MethodRelease
const MethodResetServerTiming = api.MethodResetServerTiming
const MethodResolveName = api.MethodResolveName
const MethodSaveHeapProfile = api.MethodSaveHeapProfile
const MethodSignatureToSignatureDeclaration = api.MethodSignatureToSignatureDeclaration
const MethodStartCPUProfile = api.MethodStartCPUProfile
const MethodStopCPUProfile = api.MethodStopCPUProfile
const MethodTypeToString = api.MethodTypeToString
const MethodTypeToTypeNode = api.MethodTypeToTypeNode
const MethodUpdateSnapshot = api.MethodUpdateSnapshot
//go:linkname NewAsyncConn github.com/microsoft/typescript-go/internal/api.NewAsyncConn
func NewAsyncConn(rwc io.ReadWriteCloser, handler api.Handler) *api.AsyncConn
//go:linkname NewAsyncConnWithProtocol github.com/microsoft/typescript-go/internal/api.NewAsyncConnWithProtocol
func NewAsyncConnWithProtocol(rwc io.ReadWriteCloser, protocol api.Protocol, handler api.Handler) *api.AsyncConn
//go:linkname NewDiagnosticResponse github.com/microsoft/typescript-go/internal/api.NewDiagnosticResponse
func NewDiagnosticResponse(d *ast.Diagnostic) *api.DiagnosticResponse
//go:linkname NewDiagnosticResponses github.com/microsoft/typescript-go/internal/api.NewDiagnosticResponses
func NewDiagnosticResponses(diags []*ast.Diagnostic) []*api.DiagnosticResponse
//go:linkname NewJSONRPCProtocol github.com/microsoft/typescript-go/internal/api.NewJSONRPCProtocol
func NewJSONRPCProtocol(rw io.ReadWriter) *api.JSONRPCProtocol
//go:linkname NewMessagePackProtocol github.com/microsoft/typescript-go/internal/api.NewMessagePackProtocol
func NewMessagePackProtocol(rw io.ReadWriter) *api.MessagePackProtocol
//go:linkname NewPipeTransport github.com/microsoft/typescript-go/internal/api.NewPipeTransport
func NewPipeTransport(path string) (*api.PipeTransport, error)
//go:linkname NewProjectResponse github.com/microsoft/typescript-go/internal/api.NewProjectResponse
func NewProjectResponse(p *project.Project) *api.ProjectResponse
//go:linkname NewSession github.com/microsoft/typescript-go/internal/api.NewSession
func NewSession(projectSession *project.Session, options *api.SessionOptions) *api.Session
//go:linkname NewStdioServer github.com/microsoft/typescript-go/internal/api.NewStdioServer
func NewStdioServer(options *api.StdioServerOptions) *api.StdioServer
//go:linkname NewStdioTransport github.com/microsoft/typescript-go/internal/api.NewStdioTransport
func NewStdioTransport(stdin io.ReadCloser, stdout io.WriteCloser) *api.StdioTransport
//go:linkname NewSyncConn github.com/microsoft/typescript-go/internal/api.NewSyncConn
func NewSyncConn(rwc io.ReadWriteCloser, protocol api.Protocol, handler api.Handler) *api.SyncConn
type NodeHandle = api.NodeHandle
type ParseConfigFileParams = api.ParseConfigFileParams
type PipeTransport = api.PipeTransport
type PrintNodeParams = api.PrintNodeParams
type ProfileParams = api.ProfileParams
type ProfileResult = api.ProfileResult
type ProjectFileChanges = api.ProjectFileChanges
//go:linkname ProjectHandle github.com/microsoft/typescript-go/internal/api.ProjectHandle
func ProjectHandle(p *project.Project) api.ProjectID
type ProjectID = api.ProjectID
type ProjectResponse = api.ProjectResponse
type Protocol = api.Protocol
type RawBinary = api.RawBinary
type ReferencedSymbolEntry = api.ReferencedSymbolEntry
type ReleaseParams = api.ReleaseParams
type ResolveNameParams = api.ResolveNameParams
type Session = api.Session
type SessionOptions = api.SessionOptions
//go:linkname SignatureHandle github.com/microsoft/typescript-go/internal/api.SignatureHandle
func SignatureHandle(sig *checker.Signature) api.SignatureID
type SignatureID = api.SignatureID
type SignatureResponse = api.SignatureResponse
type SignatureToSignatureDeclarationParams = api.SignatureToSignatureDeclarationParams
type SignatureUsageResponse = api.SignatureUsageResponse
type SnapshotChanges = api.SnapshotChanges
type SnapshotID = api.SnapshotID
type SourceFileMetadata = api.SourceFileMetadata
type SourceFileResponse = api.SourceFileResponse
type StdioServer = api.StdioServer
type StdioServerOptions = api.StdioServerOptions
type StdioTransport = api.StdioTransport
//go:linkname SymbolHandle github.com/microsoft/typescript-go/internal/api.SymbolHandle
func SymbolHandle(symbol *ast.Symbol) api.SymbolID
type SymbolID = api.SymbolID
type SymbolResponse = api.SymbolResponse
type SyncConn = api.SyncConn
type Transport = api.Transport
//go:linkname TypeHandle github.com/microsoft/typescript-go/internal/api.TypeHandle
func TypeHandle(t *checker.Type) api.TypeID
type TypeID = api.TypeID
type TypePredicateResponse = api.TypePredicateResponse
type TypeResponse = api.TypeResponse
type TypeToTypeNodeParams = api.TypeToTypeNodeParams
type UpdateSnapshotParams = api.UpdateSnapshotParams
type UpdateSnapshotResponse = api.UpdateSnapshotResponse
type WellKnownSymbolsResponse = api.WellKnownSymbolsResponse
