
// Code generated by _tools/gen_shims. DO NOT EDIT.

package format

import "context"
import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/format"
import "github.com/microsoft/typescript-go/internal/ls/lsutil"
import _ "unsafe"

//go:linkname FindFirstNonWhitespaceColumn github.com/microsoft/typescript-go/internal/format.FindFirstNonWhitespaceColumn
func FindFirstNonWhitespaceColumn(startPos int, endPos int, sourceFile *ast.SourceFile, options lsutil.FormatCodeSettings) int
//go:linkname FormatDocument github.com/microsoft/typescript-go/internal/format.FormatDocument
func FormatDocument(ctx context.Context, sourceFile *ast.SourceFile) []core.TextChange
//go:linkname FormatNodeGivenIndentation github.com/microsoft/typescript-go/internal/format.FormatNodeGivenIndentation
func FormatNodeGivenIndentation(ctx context.Context, node *ast.Node, file *ast.SourceFile, languageVariant core.LanguageVariant, initialIndentation int, delta int) []core.TextChange
//go:linkname FormatOnClosingCurly github.com/microsoft/typescript-go/internal/format.FormatOnClosingCurly
func FormatOnClosingCurly(ctx context.Context, sourceFile *ast.SourceFile, position int) []core.TextChange
//go:linkname FormatOnEnter github.com/microsoft/typescript-go/internal/format.FormatOnEnter
func FormatOnEnter(ctx context.Context, sourceFile *ast.SourceFile, position int) []core.TextChange
//go:linkname FormatOnOpeningCurly github.com/microsoft/typescript-go/internal/format.FormatOnOpeningCurly
func FormatOnOpeningCurly(ctx context.Context, sourceFile *ast.SourceFile, position int) []core.TextChange
//go:linkname FormatOnSemicolon github.com/microsoft/typescript-go/internal/format.FormatOnSemicolon
func FormatOnSemicolon(ctx context.Context, sourceFile *ast.SourceFile, position int) []core.TextChange
type FormatRequestKind = format.FormatRequestKind
const FormatRequestKindFormatDocument = format.FormatRequestKindFormatDocument
const FormatRequestKindFormatOnClosingCurlyBrace = format.FormatRequestKindFormatOnClosingCurlyBrace
const FormatRequestKindFormatOnEnter = format.FormatRequestKindFormatOnEnter
const FormatRequestKindFormatOnOpeningCurlyBrace = format.FormatRequestKindFormatOnOpeningCurlyBrace
const FormatRequestKindFormatOnSemicolon = format.FormatRequestKindFormatOnSemicolon
const FormatRequestKindFormatSelection = format.FormatRequestKindFormatSelection
//go:linkname FormatSelection github.com/microsoft/typescript-go/internal/format.FormatSelection
func FormatSelection(ctx context.Context, sourceFile *ast.SourceFile, start int, end int) []core.TextChange
//go:linkname FormatSpan github.com/microsoft/typescript-go/internal/format.FormatSpan
func FormatSpan(ctx context.Context, span core.TextRange, file *ast.SourceFile, kind format.FormatRequestKind) []core.TextChange
type FormattingContext = format.FormattingContext
//go:linkname GetContainingList github.com/microsoft/typescript-go/internal/format.GetContainingList
func GetContainingList(node *ast.Node, sourceFile *ast.SourceFile) *ast.NodeList
//go:linkname GetFormatCodeSettingsFromContext github.com/microsoft/typescript-go/internal/format.GetFormatCodeSettingsFromContext
func GetFormatCodeSettingsFromContext(ctx context.Context) lsutil.FormatCodeSettings
//go:linkname GetIndentation github.com/microsoft/typescript-go/internal/format.GetIndentation
func GetIndentation(position int, sourceFile *ast.SourceFile, options lsutil.FormatCodeSettings, assumeNewLineBeforeCloseBrace bool) int
//go:linkname GetIndentationForNode github.com/microsoft/typescript-go/internal/format.GetIndentationForNode
func GetIndentationForNode(n *ast.Node, ignoreActualIndentationRange *core.TextRange, sourceFile *ast.SourceFile, options lsutil.FormatCodeSettings) int
//go:linkname GetLineStartPositionForPosition github.com/microsoft/typescript-go/internal/format.GetLineStartPositionForPosition
func GetLineStartPositionForPosition(position int, sourceFile *ast.SourceFile) int
//go:linkname GetNewLineOrDefaultFromContext github.com/microsoft/typescript-go/internal/format.GetNewLineOrDefaultFromContext
func GetNewLineOrDefaultFromContext(ctx context.Context) string
type LineAction = format.LineAction
const LineActionLineAdded = format.LineActionLineAdded
const LineActionLineRemoved = format.LineActionLineRemoved
const LineActionNone = format.LineActionNone
//go:linkname NewFormattingContext github.com/microsoft/typescript-go/internal/format.NewFormattingContext
func NewFormattingContext(file *ast.SourceFile, kind format.FormatRequestKind, options lsutil.FormatCodeSettings) *format.FormattingContext
//go:linkname NewTextRangeWithKind github.com/microsoft/typescript-go/internal/format.NewTextRangeWithKind
func NewTextRangeWithKind(pos int, end int, kind ast.Kind) format.TextRangeWithKind
//go:linkname NodeWillIndentChild github.com/microsoft/typescript-go/internal/format.NodeWillIndentChild
func NodeWillIndentChild(settings lsutil.FormatCodeSettings, parent *ast.Node, child *ast.Node, sourceFile *ast.SourceFile, indentByDefault bool) bool
type RulesPosition = format.RulesPosition
const RulesPositionContextRulesAny = format.RulesPositionContextRulesAny
const RulesPositionContextRulesSpecific = format.RulesPositionContextRulesSpecific
const RulesPositionNoContextRulesAny = format.RulesPositionNoContextRulesAny
const RulesPositionNoContextRulesSpecific = format.RulesPositionNoContextRulesSpecific
const RulesPositionStopRulesAny = format.RulesPositionStopRulesAny
const RulesPositionStopRulesSpecific = format.RulesPositionStopRulesSpecific
//go:linkname ShouldIndentChildNode github.com/microsoft/typescript-go/internal/format.ShouldIndentChildNode
func ShouldIndentChildNode(settings lsutil.FormatCodeSettings, parent *ast.Node, child *ast.Node, sourceFile *ast.SourceFile, isNextChildArg ...bool) bool
type TextRangeWithKind = format.TextRangeWithKind
//go:linkname WithFormatCodeSettings github.com/microsoft/typescript-go/internal/format.WithFormatCodeSettings
func WithFormatCodeSettings(ctx context.Context, options lsutil.FormatCodeSettings, newLine string) context.Context
