
// Code generated by _tools/gen_shims. DO NOT EDIT.

package ls

import "context"
import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/checker"
import "github.com/microsoft/typescript-go/internal/compiler"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/ls"
import "github.com/microsoft/typescript-go/internal/ls/lsconv"
import "github.com/microsoft/typescript-go/internal/ls/lsutil"
import "github.com/microsoft/typescript-go/internal/lsp/lsproto"
import "github.com/microsoft/typescript-go/internal/sourcemap"
import "github.com/microsoft/typescript-go/internal/tspath"
import "unsafe"

var AfterCompletionCallback = ls.AfterCompletionCallback
var AfterDocumentSymbolsCallback = ls.AfterDocumentSymbolsCallback
var AfterInlayHintsCallback = ls.AfterInlayHintsCallback
var AfterQuickInfoCallback = ls.AfterQuickInfoCallback
type CallHierarchyDeclaration = ls.CallHierarchyDeclaration
type CandidateOrTypeInfo = ls.CandidateOrTypeInfo
//go:linkname ClientSupportsDocumentChanges github.com/microsoft/typescript-go/internal/ls.ClientSupportsDocumentChanges
func ClientSupportsDocumentChanges(ctx context.Context) bool
//go:linkname ClientSupportsRenameResourceOperations github.com/microsoft/typescript-go/internal/ls.ClientSupportsRenameResourceOperations
func ClientSupportsRenameResourceOperations(ctx context.Context) bool
//go:linkname ClientSupportsWillRenameFiles github.com/microsoft/typescript-go/internal/ls.ClientSupportsWillRenameFiles
func ClientSupportsWillRenameFiles(ctx context.Context) bool
type CodeAction = ls.CodeAction
type CodeFixContext = ls.CodeFixContext
type CodeFixProvider = ls.CodeFixProvider
type CombinedCodeActions = ls.CombinedCodeActions
//go:linkname CompareCompletionEntries github.com/microsoft/typescript-go/internal/ls.CompareCompletionEntries
func CompareCompletionEntries(a *lsproto.CompletionItem, b *lsproto.CompletionItem) int
type CompletionItem = ls.CompletionItem
type CompletionKind = ls.CompletionKind
const CompletionKindGlobal = ls.CompletionKindGlobal
const CompletionKindMemberLike = ls.CompletionKindMemberLike
const CompletionKindNone = ls.CompletionKindNone
const CompletionKindObjectPropertyDeclaration = ls.CompletionKindObjectPropertyDeclaration
const CompletionKindPropertyAccess = ls.CompletionKindPropertyAccess
const CompletionKindString = ls.CompletionKindString
type CompletionList = ls.CompletionList
type CompletionsTriggerCharacter = ls.CompletionsTriggerCharacter
type CrossProjectOrchestrator = ls.CrossProjectOrchestrator
type DeclarationInfo = ls.DeclarationInfo
type Definition = ls.Definition
type DefinitionKind = ls.DefinitionKind
//go:linkname DeprecateSortText github.com/microsoft/typescript-go/internal/ls.DeprecateSortText
func DeprecateSortText(original ls.SortText) ls.SortText
var ErrNeedsAutoImports = ls.ErrNeedsAutoImports
var ErrNoSourceFile = ls.ErrNoSourceFile
var ErrNoTokenAtPosition = ls.ErrNoTokenAtPosition
type ExportInfo = ls.ExportInfo
type ExportKind = ls.ExportKind
const ExportKindDefault = ls.ExportKindDefault
const ExportKindExportEquals = ls.ExportKindExportEquals
const ExportKindModule = ls.ExportKindModule
const ExportKindNamed = ls.ExportKindNamed
const ExportKindUMD = ls.ExportKindUMD
var FixClassIncorrectlyImplementsInterfaceProvider = ls.FixClassIncorrectlyImplementsInterfaceProvider
type Host = ls.Host
type ImpExpKind = ls.ImpExpKind
const ImpExpKindExport = ls.ImpExpKindExport
const ImpExpKindImport = ls.ImpExpKindImport
const ImpExpKindUnknown = ls.ImpExpKindUnknown
type ImportExportSymbol = ls.ImportExportSymbol
var ImportFixProvider = ls.ImportFixProvider
type ImportTracker = ls.ImportTracker
type ImportsResult = ls.ImportsResult
//go:linkname IsInString github.com/microsoft/typescript-go/internal/ls.IsInString
func IsInString(sourceFile *ast.SourceFile, position int, previousToken *ast.Node) bool
var IsolatedDeclarationsFixProvider = ls.IsolatedDeclarationsFixProvider
type JSDocTagInfo = ls.JSDocTagInfo
type KeywordCompletionFilters = ls.KeywordCompletionFilters
const KeywordCompletionFiltersAll = ls.KeywordCompletionFiltersAll
const KeywordCompletionFiltersClassElementKeywords = ls.KeywordCompletionFiltersClassElementKeywords
const KeywordCompletionFiltersConstructorParameterKeywords = ls.KeywordCompletionFiltersConstructorParameterKeywords
const KeywordCompletionFiltersFunctionLikeBodyKeywords = ls.KeywordCompletionFiltersFunctionLikeBodyKeywords
const KeywordCompletionFiltersInterfaceElementKeywords = ls.KeywordCompletionFiltersInterfaceElementKeywords
const KeywordCompletionFiltersLast = ls.KeywordCompletionFiltersLast
const KeywordCompletionFiltersNone = ls.KeywordCompletionFiltersNone
const KeywordCompletionFiltersTypeAssertionKeywords = ls.KeywordCompletionFiltersTypeAssertionKeywords
const KeywordCompletionFiltersTypeKeyword = ls.KeywordCompletionFiltersTypeKeyword
const KeywordCompletionFiltersTypeKeywords = ls.KeywordCompletionFiltersTypeKeywords
type LanguageService = ls.LanguageService
//go:linkname LanguageService_getQuickInfoAndDocumentationForSymbol github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getQuickInfoAndDocumentationForSymbol
func LanguageService_getQuickInfoAndDocumentationForSymbol(recv *ls.LanguageService, c *checker.Checker, symbol *ast.Symbol, node *ast.Node, contentFormat lsproto.MarkupKind, vc *checker.VerbosityContext) (string, string)
type extra_LanguageService struct {
  projectPath tspath.Path
  host ls.Host
  activeConfig lsutil.UserPreferences
  program *compiler.Program
  converters *lsconv.Converters
  documentPositionMappers map[string]*sourcemap.DocumentPositionMapper
}
func LanguageService_converters(v *ls.LanguageService) *lsconv.Converters {
  return ((*extra_LanguageService)(unsafe.Pointer(v))).converters
}
type LocationAndSymbol = ls.LocationAndSymbol
type ModuleReference = ls.ModuleReference
type ModuleReferenceKind = ls.ModuleReferenceKind
const ModuleReferenceKindImplicit = ls.ModuleReferenceKindImplicit
const ModuleReferenceKindImport = ls.ModuleReferenceKindImport
const ModuleReferenceKindReference = ls.ModuleReferenceKindReference
//go:linkname NewLanguageService github.com/microsoft/typescript-go/internal/ls.NewLanguageService
func NewLanguageService(projectPath tspath.Path, program *compiler.Program, host ls.Host, activeFile string) *ls.LanguageService
//go:linkname NewSymbolAndEntries github.com/microsoft/typescript-go/internal/ls.NewSymbolAndEntries
func NewSymbolAndEntries(kind ls.DefinitionKind, node *ast.Node, symbol *ast.Symbol, references []*ls.ReferenceEntry) *ls.SymbolAndEntries
type PossibleTypeArgumentInfo = ls.PossibleTypeArgumentInfo
type Project = ls.Project
//go:linkname ProvideWorkspaceSymbols github.com/microsoft/typescript-go/internal/ls.ProvideWorkspaceSymbols
func ProvideWorkspaceSymbols(ctx context.Context, programs []*compiler.Program, converters *lsconv.Converters, preferences lsutil.UserPreferences, query string) (lsproto.WorkspaceSymbolResponse, error)
//go:linkname RangeContainsRange github.com/microsoft/typescript-go/internal/ls.RangeContainsRange
func RangeContainsRange(r1 core.TextRange, r2 core.TextRange) bool
type RefactorProvider = ls.RefactorProvider
type ReferenceEntry = ls.ReferenceEntry
//go:linkname RegisterAfterCompletionCallback github.com/microsoft/typescript-go/internal/ls.RegisterAfterCompletionCallback
func RegisterAfterCompletionCallback(cb func(ctx context.Context, sf *ast.SourceFile, position int, items []*lsproto.CompletionItem, program *compiler.Program, langService *ls.LanguageService) []*lsproto.CompletionItem)
//go:linkname RegisterAfterDocumentSymbolsCallback github.com/microsoft/typescript-go/internal/ls.RegisterAfterDocumentSymbolsCallback
func RegisterAfterDocumentSymbolsCallback(cb func(ctx context.Context, sf *ast.SourceFile, symbols []*lsproto.DocumentSymbol, program *compiler.Program, langService *ls.LanguageService) []*lsproto.DocumentSymbol)
//go:linkname RegisterAfterInlayHintsCallback github.com/microsoft/typescript-go/internal/ls.RegisterAfterInlayHintsCallback
func RegisterAfterInlayHintsCallback(cb func(program checker.Program, c *checker.Checker, sf *ast.SourceFile, span core.TextRange, preferences *lsutil.InlayHintsPreferences, hints []*lsproto.InlayHint, converters *lsconv.Converters) []*lsproto.InlayHint)
//go:linkname RegisterAfterQuickInfoCallback github.com/microsoft/typescript-go/internal/ls.RegisterAfterQuickInfoCallback
func RegisterAfterQuickInfoCallback(cb func(program checker.Program, c *checker.Checker, sf *ast.SourceFile, node *ast.Node, symbol *ast.Symbol, quickInfo string, documentation string, isMarkdown bool) (string, string, *ast.Node))
//go:linkname RegisterCodeFixProvider github.com/microsoft/typescript-go/internal/ls.RegisterCodeFixProvider
func RegisterCodeFixProvider(provider *ls.CodeFixProvider)
//go:linkname RegisterRefactorProvider github.com/microsoft/typescript-go/internal/ls.RegisterRefactorProvider
func RegisterRefactorProvider(provider *ls.RefactorProvider)
type RenameInfo = ls.RenameInfo
//go:linkname SemanticTokensLegend github.com/microsoft/typescript-go/internal/ls.SemanticTokensLegend
func SemanticTokensLegend(clientCapabilities lsproto.ResolvedSemanticTokensClientCapabilities) *lsproto.SemanticTokensLegend
type SignatureUsage = ls.SignatureUsage
type SortText = ls.SortText
const SortTextAutoImportSuggestions = ls.SortTextAutoImportSuggestions
const SortTextClassMemberSnippets = ls.SortTextClassMemberSnippets
const SortTextGlobalsOrKeywords = ls.SortTextGlobalsOrKeywords
const SortTextJavascriptIdentifiers = ls.SortTextJavascriptIdentifiers
const SortTextLocalDeclarationPriority = ls.SortTextLocalDeclarationPriority
const SortTextLocationPriority = ls.SortTextLocationPriority
const SortTextMemberDeclaredBySpreadAssignment = ls.SortTextMemberDeclaredBySpreadAssignment
const SortTextOptionalMember = ls.SortTextOptionalMember
const SortTextSuggestedClassMembers = ls.SortTextSuggestedClassMembers
const SourceClassMemberSnippet = ls.SourceClassMemberSnippet
const SourceObjectLiteralMemberWithComma = ls.SourceObjectLiteralMemberWithComma
const SourceObjectLiteralMethodSnippet = ls.SourceObjectLiteralMethodSnippet
const SourceSwitchCases = ls.SourceSwitchCases
const SourceThisProperty = ls.SourceThisProperty
const SourceTypeOnlyAlias = ls.SourceTypeOnlyAlias
type SymbolAndEntries = ls.SymbolAndEntries
type SymbolAndEntriesData = ls.SymbolAndEntriesData
var TriggerCharacters = ls.TriggerCharacters
//go:linkname GetJSDocOrTag github.com/microsoft/typescript-go/internal/ls.getJSDocOrTag
func GetJSDocOrTag(c *checker.Checker, node *ast.Node) *ast.Node
