
// Code generated by _tools/gen_shims. DO NOT EDIT.

package vfsmatch

import "github.com/microsoft/typescript-go/internal/vfs"
import "github.com/microsoft/typescript-go/internal/vfs/vfsmatch"
import _ "unsafe"

//go:linkname IsImplicitGlob github.com/microsoft/typescript-go/internal/vfs/vfsmatch.IsImplicitGlob
func IsImplicitGlob(lastPathComponent string) bool
//go:linkname NewSpecMatcher github.com/microsoft/typescript-go/internal/vfs/vfsmatch.NewSpecMatcher
func NewSpecMatcher(specs []string, basePath string, usage vfsmatch.Usage, useCaseSensitiveFileNames bool) *vfsmatch.SpecMatcher
//go:linkname ReadDirectory github.com/microsoft/typescript-go/internal/vfs/vfsmatch.ReadDirectory
func ReadDirectory(host vfs.FS, currentDir string, path string, extensions []string, excludes []string, includes []string, depth int) []string
type SpecMatcher = vfsmatch.SpecMatcher
const UnlimitedDepth = vfsmatch.UnlimitedDepth
type Usage = vfsmatch.Usage
const UsageDirectories = vfsmatch.UsageDirectories
const UsageExclude = vfsmatch.UsageExclude
const UsageFiles = vfsmatch.UsageFiles
