
// Code generated by _tools/gen_shims. DO NOT EDIT.

package lsptestutil

import "github.com/microsoft/typescript-go/internal/lsp"
import "github.com/microsoft/typescript-go/internal/testutil/lsptestutil"
import "testing"
import _ "unsafe"

type LSPClient = lsptestutil.LSPClient
//go:linkname NewLSPClient github.com/microsoft/typescript-go/internal/testutil/lsptestutil.NewLSPClient
func NewLSPClient(t *testing.T, serverOpts lsp.ServerOptions, onServerRequest lsptestutil.ServerRequestHandler) (*lsptestutil.LSPClient, func() error)
type ServerNotificationHandler = lsptestutil.ServerNotificationHandler
type ServerRequestHandler = lsptestutil.ServerRequestHandler
