import type { PackageManifestContribution } from './modifier/package-manifest-contributions'
import type { ComposeDSL } from './services/planner'
import type { TemplatePath } from '@/brand/template-path'
import type {
  GenerationPackageSpec,
  InternalDependencyLink,
} from '@/schema/generation-package-spec'
import type {
  CliProjectConfig,
  LibraryProjectConfig,
  NodeProjectConfig,
  ProjectConfig,
  ReactProjectConfig,
  VueProjectConfig,
  WorkspaceRootConfig,
} from '@/schema/project-config'
import { makeProjectName } from '@/brand/project-name'
import {
  buildPackageManifestJson,
  getPackageManifestContributions,
} from '@/core/modifier/package-json'
import { packageManifestTargetPath } from '@/core/modifier/package-manifest-contributions'
import {
  CliPackageOwner,
  contributionTrace,
  ContributionUnitKind,
  FrontendPackageOwner,
  LibraryPackageOwner,
  NodePackageOwner,
} from '@/core/ownership/model'
import { buildRootSvg } from '@/core/template-registry/root-svg'
import { isFrontendProject } from '@/utils/type-guard'
import { buildTemplates } from './services/compose'

type WorkspacePackageProjectConfig
  = | ReactProjectConfig
    | VueProjectConfig
    | NodeProjectConfig
    | CliProjectConfig
    | LibraryProjectConfig

function assertNever(value: never): never {
  throw new Error(`Unreachable case: ${String(value)}`)
}

function workspacePackageTargetDirectory(spec: GenerationPackageSpec): string {
  switch (spec.kind) {
    case 'frontend-app':
    case 'backend-app':
    case 'worker-app':
    case 'cli-tool':
      return `apps/${spec.id}`
    case 'library-package':
      return `libs/${spec.id}`
    default:
      return assertNever(spec)
  }
}

function workspacePackageJsonOwner(spec: GenerationPackageSpec) {
  switch (spec.kind) {
    case 'frontend-app':
      return FrontendPackageOwner
    case 'backend-app':
    case 'worker-app':
      return NodePackageOwner
    case 'cli-tool':
      return CliPackageOwner
    case 'library-package':
      return LibraryPackageOwner
    default:
      return assertNever(spec)
  }
}

function workspacePackageProjectConfig(
  rootConfig: WorkspaceRootConfig,
  spec: GenerationPackageSpec,
): WorkspacePackageProjectConfig {
  const base = {
    name: makeProjectName(String(spec.id)),
    git: rootConfig.git,
    linting: rootConfig.linting,
    codeQuality: rootConfig.codeQuality,
  }

  switch (spec.kind) {
    case 'frontend-app':
      if (spec.frontend.framework === 'react') {
        return {
          ...base,
          type: 'react',
          language: rootConfig.language,
          buildTool: spec.frontend.buildTool,
          cssPreprocessor: spec.frontend.cssPreprocessor,
          cssFramework: spec.frontend.cssFramework,
          router: 'none',
          stateManagement: 'none',
        }
      }

      return {
        ...base,
        type: 'vue',
        language: rootConfig.language,
        buildTool: spec.frontend.buildTool,
        cssPreprocessor: spec.frontend.cssPreprocessor,
        cssFramework: spec.frontend.cssFramework,
        router: false,
        stateManagement: false,
      }
    case 'backend-app':
      return {
        ...base,
        type: 'node',
        language: 'typescript',
      }
    case 'cli-tool':
      return {
        ...base,
        type: 'cli',
        language: 'typescript',
        toolkit: spec.cli.toolkit,
      }
    case 'library-package':
      return {
        ...base,
        type: 'library',
        language: 'typescript',
        runtime: spec.runtime,
      }
    case 'worker-app':
      throw new Error('Workspace worker app generation is not available yet.')
    default:
      return assertNever(spec)
  }
}

export function workspacePackageProjectConfigs(
  rootConfig: WorkspaceRootConfig,
): readonly WorkspacePackageProjectConfig[] {
  return rootConfig.packages.map(spec => workspacePackageProjectConfig(rootConfig, spec))
}

function workspacePackageDescription(spec: GenerationPackageSpec): string {
  switch (spec.kind) {
    case 'frontend-app':
      return `A ${spec.frontend.framework} workspace app generated by @sayoriqwq/prelude`
    case 'backend-app':
      return 'A Node workspace app generated by @sayoriqwq/prelude'
    case 'cli-tool':
      return 'A workspace CLI tool generated by @sayoriqwq/prelude'
    case 'library-package':
      return 'A workspace library package generated by @sayoriqwq/prelude'
    case 'worker-app':
      return 'A workspace worker app generated by @sayoriqwq/prelude'
    default:
      return assertNever(spec)
  }
}

function baseWorkspacePackageJson(spec: GenerationPackageSpec) {
  return {
    name: spec.name,
    type: 'module',
    version: '0.0.0',
    description: workspacePackageDescription(spec),
    license: 'MIT',
    engines: {
      node: '>=22.22.1',
    },
    scripts: {},
    dependencies: {},
    devDependencies: {},
  }
}

function resolveInternalDependencyTarget(
  link: InternalDependencyLink,
  packages: readonly GenerationPackageSpec[],
): GenerationPackageSpec {
  const target = packages.find(candidate =>
    link.target.by === 'id'
      ? candidate.id === link.target.id
      : candidate.name === link.target.name,
  )

  if (!target) {
    const label = link.target.by === 'id'
      ? `id "${link.target.id}"`
      : `name "${link.target.name}"`
    throw new Error(`Workspace package internal dependency target not found by ${label}.`)
  }

  return target
}

function getInternalWorkspaceDependencyContribution(
  spec: GenerationPackageSpec,
  packages: readonly GenerationPackageSpec[],
): PackageManifestContribution[] {
  if (spec.internalDependencies.length === 0) {
    return []
  }

  const dependencies: Record<string, string> = {}
  for (const link of spec.internalDependencies) {
    const target = resolveInternalDependencyTarget(link, packages)
    dependencies[String(link.alias ?? target.name)] = 'workspace:*'
  }

  return [{
    ownership: contributionTrace(workspacePackageJsonOwner(spec), ContributionUnitKind.JsonTextMutation),
    targetScope: 'package',
    sections: {
      dependencies,
    },
  }]
}

function buildWorkspacePackage(
  dsl: ComposeDSL,
  templateRoot: TemplatePath,
  rootConfig: WorkspaceRootConfig,
  spec: GenerationPackageSpec,
) {
  const packageConfig = workspacePackageProjectConfig(rootConfig, spec) as ProjectConfig
  const targetDirectory = workspacePackageTargetDirectory(spec)

  if (isFrontendProject(packageConfig)) {
    buildRootSvg(dsl, templateRoot, { targetDirectory })
  }

  buildPackageManifestJson(dsl, {
    targetPath: packageManifestTargetPath(targetDirectory),
    targetScope: 'package',
    base: () => baseWorkspacePackageJson(spec),
    contributions: [
      ...getPackageManifestContributions(packageConfig),
      ...getInternalWorkspaceDependencyContribution(spec, rootConfig.packages),
    ],
    ownership: contributionTrace(workspacePackageJsonOwner(spec), ContributionUnitKind.JsonTextMutation),
  })

  buildTemplates(dsl, templateRoot, packageConfig, {
    targetScope: 'package',
    targetDirectory,
    renderConfig: packageConfig,
  })
}

export function buildWorkspacePackages(
  dsl: ComposeDSL,
  templateRoot: TemplatePath,
  rootConfig: WorkspaceRootConfig,
) {
  for (const spec of rootConfig.packages) {
    buildWorkspacePackage(dsl, templateRoot, rootConfig, spec)
  }
}
