
// Code generated by _tools/gen_shims. DO NOT EDIT.

package astnav

import "github.com/microsoft/typescript-go/internal/ast"
import _ "github.com/microsoft/typescript-go/internal/astnav"
import _ "unsafe"

//go:linkname FindChildOfKind github.com/microsoft/typescript-go/internal/astnav.FindChildOfKind
func FindChildOfKind(containingNode *ast.Node, kind ast.Kind, sourceFile *ast.SourceFile) *ast.Node
//go:linkname FindNextToken github.com/microsoft/typescript-go/internal/astnav.FindNextToken
func FindNextToken(previousToken *ast.Node, parent *ast.Node, file *ast.SourceFile) *ast.Node
//go:linkname FindPrecedingToken github.com/microsoft/typescript-go/internal/astnav.FindPrecedingToken
func FindPrecedingToken(sourceFile *ast.SourceFile, position int) *ast.Node
//go:linkname FindPrecedingTokenEx github.com/microsoft/typescript-go/internal/astnav.FindPrecedingTokenEx
func FindPrecedingTokenEx(sourceFile *ast.SourceFile, position int, startNode *ast.Node, excludeJSDoc bool) *ast.Node
//go:linkname GetStartOfNode github.com/microsoft/typescript-go/internal/astnav.GetStartOfNode
func GetStartOfNode(node *ast.Node, file *ast.SourceFile, includeJSDoc bool) int
//go:linkname GetTokenAtPosition github.com/microsoft/typescript-go/internal/astnav.GetTokenAtPosition
func GetTokenAtPosition(sourceFile *ast.SourceFile, position int) *ast.Node
//go:linkname GetTouchingPropertyName github.com/microsoft/typescript-go/internal/astnav.GetTouchingPropertyName
func GetTouchingPropertyName(sourceFile *ast.SourceFile, position int) *ast.Node
//go:linkname GetTouchingToken github.com/microsoft/typescript-go/internal/astnav.GetTouchingToken
func GetTouchingToken(sourceFile *ast.SourceFile, position int) *ast.Node
//go:linkname VisitEachChildAndJSDoc github.com/microsoft/typescript-go/internal/astnav.VisitEachChildAndJSDoc
func VisitEachChildAndJSDoc(node *ast.Node, sourceFile *ast.SourceFile, visitNode func(*ast.Node, *ast.NodeVisitor) *ast.Node, visitNodes func(*ast.NodeList, *ast.NodeVisitor) *ast.NodeList)
