packages:
  - "testdata/tests/effect-v3"
  - "testdata/tests/effect-v3-refactors"
  - "testdata/tests/effect-v4"
  - "testdata/tests/effect-v4-document-symbols"
  - "testdata/tests/effect-v4-refactors"
  - "_packages/*"
catalog:
  "@changesets/cli": ^2.30.0
  "@effect/platform-node": ^4.0.0-beta.83
  "@effect/platform-node-shared": ^4.0.0-beta.83
  "@standard-schema/spec": ^1.1.0
  "@types/node": ^22.0.0
  effect: 4.0.0-beta.83
  fast-check: ^4.4.0
  pure-rand: ^7.0.0
  tsdown: ^0.20.1
  typescript: next
  vitest: ^3.2.1
