
// Code generated by _tools/gen_shims. DO NOT EDIT.

package project

import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/ls/autoimport"
import "github.com/microsoft/typescript-go/internal/ls/lsutil"
import "github.com/microsoft/typescript-go/internal/project"
import "github.com/microsoft/typescript-go/internal/project/logging"
import "github.com/microsoft/typescript-go/internal/tspath"
import "github.com/zeebo/xxh3"
import _ "unsafe"

type APISnapshotRequest = project.APISnapshotRequest
type APIState = project.APIState
type ATAStateChange = project.ATAStateChange
type CheckerPoolOptions = project.CheckerPoolOptions
type Client = project.Client
type ConfigFileRegistry = project.ConfigFileRegistry
type CreateProgramResult = project.CreateProgramResult
type ExtendedConfigCache = project.ExtendedConfigCache
type ExtendedConfigCacheEntry = project.ExtendedConfigCacheEntry
type ExtendedConfigParseArgs = project.ExtendedConfigParseArgs
type FileChange = project.FileChange
type FileChangeKind = project.FileChangeKind
const FileChangeKindChange = project.FileChangeKindChange
const FileChangeKindClose = project.FileChangeKindClose
const FileChangeKindOpen = project.FileChangeKindOpen
const FileChangeKindSave = project.FileChangeKindSave
const FileChangeKindWatchChange = project.FileChangeKindWatchChange
const FileChangeKindWatchCreate = project.FileChangeKindWatchCreate
const FileChangeKindWatchDelete = project.FileChangeKindWatchDelete
type FileChangeSummary = project.FileChangeSummary
type FileContent = project.FileContent
type FileHandle = project.FileHandle
type FileSource = project.FileSource
type Kind = project.Kind
const KindConfigured = project.KindConfigured
const KindInferred = project.KindInferred
//go:linkname NewConfiguredProject github.com/microsoft/typescript-go/internal/project.NewConfiguredProject
func NewConfiguredProject(configFileName string, configFilePath tspath.Path, builder *project.ProjectCollectionBuilder, logger *logging.LogTree) *project.Project
//go:linkname NewExtendedConfigCache github.com/microsoft/typescript-go/internal/project.NewExtendedConfigCache
func NewExtendedConfigCache() *project.ExtendedConfigCache
//go:linkname NewInferredProject github.com/microsoft/typescript-go/internal/project.NewInferredProject
func NewInferredProject(currentDirectory string, compilerOptions *core.CompilerOptions, rootFileNames []string, builder *project.ProjectCollectionBuilder, logger *logging.LogTree) *project.Project
//go:linkname NewParseCache github.com/microsoft/typescript-go/internal/project.NewParseCache
func NewParseCache(options project.RefCountCacheOptions) *project.ParseCache
//go:linkname NewParseCacheKey github.com/microsoft/typescript-go/internal/project.NewParseCacheKey
func NewParseCacheKey(options ast.SourceFileParseOptions, hash xxh3.Uint128, scriptKind core.ScriptKind) project.ParseCacheKey
//go:linkname NewProject github.com/microsoft/typescript-go/internal/project.NewProject
func NewProject(configFileName string, kind project.Kind, currentDirectory string, builder *project.ProjectCollectionBuilder, logger *logging.LogTree) *project.Project
//go:linkname NewSession github.com/microsoft/typescript-go/internal/project.NewSession
func NewSession(init *project.SessionInit) *project.Session
//go:linkname NewSnapshot github.com/microsoft/typescript-go/internal/project.NewSnapshot
func NewSnapshot(id uint64, fs *project.SnapshotFS, sessionOptions *project.SessionOptions, configFileRegistry *project.ConfigFileRegistry, compilerOptionsForInferredProjects *core.CompilerOptions, userPreferences lsutil.UserPreferences, autoImports *autoimport.Registry, autoImportsWatch *project.WatchedFiles[map[tspath.Path]string], toPath func(fileName string) tspath.Path) *project.Snapshot
type Overlay = project.Overlay
type OwnerCache[K comparable, V, LoadArgs any] = project.OwnerCache[K,V,LoadArgs]
type ParseCache = project.ParseCache
type ParseCacheKey = project.ParseCacheKey
type PatternsAndIgnored = project.PatternsAndIgnored
type PendingReload = project.PendingReload
const PendingReloadFileNames = project.PendingReloadFileNames
const PendingReloadFull = project.PendingReloadFull
const PendingReloadNone = project.PendingReloadNone
type ProgramUpdateKind = project.ProgramUpdateKind
const ProgramUpdateKindCloned = project.ProgramUpdateKindCloned
const ProgramUpdateKindNewFiles = project.ProgramUpdateKindNewFiles
const ProgramUpdateKindNone = project.ProgramUpdateKindNone
const ProgramUpdateKindSameFileNames = project.ProgramUpdateKindSameFileNames
type Project = project.Project
type ProjectCollection = project.ProjectCollection
type ProjectCollectionBuilder = project.ProjectCollectionBuilder
type ProjectTreeRequest = project.ProjectTreeRequest
type RefCountCache[K comparable, V, AcquireArgs any] = project.RefCountCache[K,V,AcquireArgs]
type RefCountCacheOptions = project.RefCountCacheOptions
type ResourceRequest = project.ResourceRequest
type Session = project.Session
type SessionInit = project.SessionInit
type SessionOptions = project.SessionOptions
type Snapshot = project.Snapshot
type SnapshotChange = project.SnapshotChange
type SnapshotFS = project.SnapshotFS
type TestConfigEntry = project.TestConfigEntry
type TestConfigFileNamesEntry = project.TestConfigFileNamesEntry
type UpdateReason = project.UpdateReason
const UpdateReasonDidChangeCompilerOptionsForInferredProjects = project.UpdateReasonDidChangeCompilerOptionsForInferredProjects
const UpdateReasonDidCloseFile = project.UpdateReasonDidCloseFile
const UpdateReasonDidOpenFile = project.UpdateReasonDidOpenFile
const UpdateReasonIdleCleanDiskCache = project.UpdateReasonIdleCleanDiskCache
const UpdateReasonRequestedLanguageServiceForFileNotOpen = project.UpdateReasonRequestedLanguageServiceForFileNotOpen
const UpdateReasonRequestedLanguageServicePendingChanges = project.UpdateReasonRequestedLanguageServicePendingChanges
const UpdateReasonRequestedLanguageServiceProjectDirty = project.UpdateReasonRequestedLanguageServiceProjectDirty
const UpdateReasonRequestedLanguageServiceProjectNotLoaded = project.UpdateReasonRequestedLanguageServiceProjectNotLoaded
const UpdateReasonRequestedLanguageServiceWithAutoImports = project.UpdateReasonRequestedLanguageServiceWithAutoImports
const UpdateReasonRequestedLoadProjectTree = project.UpdateReasonRequestedLoadProjectTree
const UpdateReasonUnknown = project.UpdateReasonUnknown
type WatchedFiles[T any] = project.WatchedFiles[T]
type WatcherID = project.WatcherID
type Watchers = project.Watchers
