#!/usr/bin/env node

import process from 'node:process'

interface Variant {
  readonly key: string
  readonly title: string
  readonly render: (width: number, height: number) => readonly string[]
}

interface ProjectPreview {
  readonly name: string
  readonly target: string
  readonly shape: string
  readonly includes: readonly string[]
  readonly managedSupport: readonly string[]
  readonly nextCommands: readonly string[]
  readonly agentCommand: string
}

const preview: ProjectPreview = {
  name: 'my-worker',
  target: './my-worker',
  shape: 'Minimal workspace',
  includes: [
    'Minimal pnpm workspace root',
    'apps/* and libs/* workspace slots',
    'pnpm workspace setup',
  ],
  managedSupport: [
    'No application package is generated by default',
    'Package abilities are added by explicit CreateSpec recipes',
    'Workspace maintain support remains a separate lifecycle slice',
  ],
  nextCommands: [
    'pnpm install',
    'add an explicit package ability recipe',
  ],
  agentCommand: 'prelude create --spec ./prelude.create.json --target ./my-worker --json --yes',
}

const variants: readonly Variant[] = [
  {
    key: '1',
    title: 'Guided setup',
    render: renderGuidedSetup,
  },
  {
    key: '2',
    title: 'Recipe gallery',
    render: renderRecipeGallery,
  },
  {
    key: '3',
    title: 'Review and create',
    render: renderReviewAndCreate,
  },
]

let currentVariantIndex = 0

function renderGuidedSetup(width: number, height: number): readonly string[] {
  const leftWidth = Math.max(34, Math.floor(width * 0.42))
  const rightWidth = Math.max(42, width - leftWidth - 5)
  const bodyHeight = Math.max(13, height - 10)

  return [
    header(width, 'prelude create'),
    callout(width, 'Ready to create', 'Choose the project shape, check the outcome, then create. Details stay one key away.'),
    row([
      panel('Project', [
        field('Name', preview.name),
        field('Location', preview.target),
        field('Starting point', preview.shape),
        '',
        'Included',
        ...preview.includes.map(item => `  [x] ${item}`),
      ], leftWidth),
      panel('What you will get', [
        'A ready workspace with:',
        '  - root package manifest',
        '  - pnpm workspace file',
        '  - apps/* and libs/* package slots',
        '',
        'After create:',
        ...preview.nextCommands.map(command => `  ${command}`),
        '',
        'Ownership',
        ...preview.managedSupport.map(item => `  - ${item}`),
      ], rightWidth),
    ], bodyHeight),
    footer(width, 'enter create  p preview details  e export spec  q quit'),
  ]
}

function renderRecipeGallery(width: number, height: number): readonly string[] {
  const leftWidth = Math.max(30, Math.floor(width * 0.34))
  const rightWidth = Math.max(50, width - leftWidth - 5)
  const bodyHeight = Math.max(14, height - 9)

  return [
    header(width, 'prelude create'),
    callout(width, 'Start from a saved shape', 'Recipes are complete CreateSpec files, not presets. Pick one, then customize only what matters.'),
    row([
      panel('Starting points', [
        '> Minimal workspace',
        '  Node CLI workspace',
        '  React app workspace',
        '  Vue app workspace',
        '  Node package',
        '  Library package',
        '',
        'Recent',
        '  sayori-tooling',
        '  agent-ready-cli',
      ], leftWidth),
      panel('Minimal workspace', [
        'Best for',
        '  A root workspace before selecting package abilities.',
        '',
        'Creates',
        `  ${preview.target}`,
        '  package slots under apps/* and libs/*',
        '',
        'Includes',
        ...preview.includes.map(item => `  - ${item}`),
        '',
        'Managed support',
        '  Maintain remains separate from create.',
      ], rightWidth),
    ], bodyHeight),
    footer(width, 'enter use recipe  c customize  e export spec  q quit'),
  ]
}

function renderReviewAndCreate(width: number, height: number): readonly string[] {
  const topWidth = Math.max(50, Math.floor(width * 0.62))
  const sideWidth = Math.max(28, width - topWidth - 5)
  const bodyHeight = Math.max(12, height - 16)

  return [
    header(width, 'prelude create'),
    steps(width, ['Choose', 'Configure', 'Review', 'Create'], 2),
    row([
      panel('Review', [
        `${preview.name}`,
        `Location: ${preview.target}`,
        `Shape: ${preview.shape}`,
        '',
        'This will create a new project start.',
        'It will not manage ordinary app code after create.',
        '',
        'Looks ready:',
        '  [x] target path is available',
        '  [x] selected tools are compatible',
        '  [x] managed support is explicit',
      ], topWidth),
      panel('Actions', [
        '[enter] Create project',
        '[p] Preview file list',
        '[e] Export CreateSpec',
        '[a] Copy agent command',
        '',
        'Agent command',
        ...wrap(preview.agentCommand, sideWidth - 4),
      ], sideWidth),
    ], bodyHeight),
    panel('Details are collapsed by default', [
      'Advanced details can show canonical CreateSpec, file plan, and maintain ownership.',
      'The default screen keeps those out of the way unless the user asks for them.',
    ], width - 2).join('\n'),
    footer(width, 'enter create  p preview details  e export spec  a agent command  q quit'),
  ].flatMap(splitLines)
}

function field(label: string, value: string): string {
  return `${label}: ${value}`
}

function panel(title: string, content: readonly string[], width: number): readonly string[] {
  const innerWidth = Math.max(1, width - 4)
  const lines = [
    `+${repeat('-', width - 2)}+`,
    `| ${padRight(title, innerWidth)} |`,
    `+${repeat('-', width - 2)}+`,
    ...content.flatMap(line => wrap(line, innerWidth)).map(line => `| ${padRight(line, innerWidth)} |`),
    `+${repeat('-', width - 2)}+`,
  ]

  return lines
}

function row(columns: readonly (readonly string[])[], minHeight: number): string {
  const height = Math.max(minHeight, ...columns.map(column => column.length))
  const paddedColumns = columns.map(column => padLines(column, height))
  const rows: string[] = []

  for (let index = 0; index < height; index += 1) {
    rows.push(paddedColumns.map(column => column[index]).join('  '))
  }

  return rows.join('\n')
}

function header(width: number, productName: string): string {
  const variant = getCurrentVariant()
  return [
    repeat('=', width),
    padRight(`${productName} | ${variant.key}. ${variant.title}`, width),
    padRight('PROTOTYPE ONLY - static terminal mock, no create/maintain logic', width),
    repeat('=', width),
  ].join('\n')
}

function callout(width: number, title: string, body: string): string {
  return [
    padRight(`${title}: ${body}`, width),
    repeat('-', width),
  ].join('\n')
}

function steps(width: number, labels: readonly string[], activeIndex: number): string {
  const parts = labels.map((label, index) => {
    if (index < activeIndex) {
      return `[x] ${label}`
    }
    if (index === activeIndex) {
      return `> ${label}`
    }
    return `[ ] ${label}`
  })

  return [
    padRight(parts.join('  ->  '), width),
    repeat('-', width),
  ].join('\n')
}

function footer(width: number, shortcuts: string): string {
  return [
    repeat('-', width),
    '[1] guided  [2] recipes  [3] review  [left/right] switch',
    shortcuts,
  ].map(line => padRight(line, width)).join('\n')
}

function render(): void {
  const width = Math.max(90, process.stdout.columns ?? 110)
  const height = Math.max(28, process.stdout.rows ?? 34)
  const variant = getCurrentVariant()
  const lines = variant.render(width, height).flatMap(splitLines)
  const croppedLines = lines.slice(0, height - 1)

  if (process.stdout.isTTY) {
    process.stdout.write('\x1B[2J\x1B[H')
  }

  process.stdout.write(`${croppedLines.join('\n')}\n`)
}

function getCurrentVariant(): Variant {
  const variant = variants[currentVariantIndex]
  if (variant !== undefined) {
    return variant
  }

  currentVariantIndex = 0
  const firstVariant = variants[0]
  if (firstVariant !== undefined) {
    return firstVariant
  }

  throw new Error('Prototype variants are missing.')
}

function splitLines(value: string): readonly string[] {
  return value.split('\n')
}

function padLines(lines: readonly string[], height: number): readonly string[] {
  const width = Math.max(...lines.map(line => line.length))
  return Array.from({ length: height }, (_, index) => padRight(lines[index] ?? '', width))
}

function padRight(value: string, width: number): string {
  if (value.length >= width) {
    return value.slice(0, width)
  }

  return `${value}${repeat(' ', width - value.length)}`
}

function repeat(value: string, count: number): string {
  return value.repeat(Math.max(0, count))
}

function wrap(value: string, width: number): readonly string[] {
  if (value.length <= width) {
    return [value]
  }

  const words = value.split(' ')
  const lines: string[] = []
  let current = ''

  for (const word of words) {
    const next = current.length === 0 ? word : `${current} ${word}`
    if (next.length > width) {
      lines.push(current)
      current = word
    }
    else {
      current = next
    }
  }

  if (current.length > 0) {
    lines.push(current)
  }

  return lines
}

function nextVariant(): void {
  currentVariantIndex = (currentVariantIndex + 1) % variants.length
}

function previousVariant(): void {
  currentVariantIndex = (currentVariantIndex + variants.length - 1) % variants.length
}

function exit(): never {
  process.stdout.write('\x1B[?25h\x1B[?1049l')
  process.exit(0)
}

if (process.stdout.isTTY && typeof process.stdin.setRawMode === 'function') {
  process.stdout.write('\x1B[?1049h\x1B[?25l')
  process.stdin.setRawMode(true)
  process.stdin.resume()
  process.stdin.setEncoding('utf8')
  process.stdin.on('data', (key) => {
    if (key === '\u0003' || key === 'q') {
      exit()
    }

    if (key === '1') {
      currentVariantIndex = 0
    }
    else if (key === '2') {
      currentVariantIndex = 1
    }
    else if (key === '3') {
      currentVariantIndex = 2
    }
    else if (key === '\x1B[C') {
      nextVariant()
    }
    else if (key === '\x1B[D') {
      previousVariant()
    }

    render()
  })
  process.stdout.on('resize', render)
  process.on('exit', () => {
    process.stdout.write('\x1B[?25h\x1B[?1049l')
  })

  render()
}
else {
  render()
  process.stdout.write('\nInteractive raw terminal mode is unavailable; rendered variant 1 once.\n')
}
